# Generated by Django 6.0.3 on 2026-03-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_diagnosis_patient_symptoms_patient_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
